Hw05 parallel execution
pavarov/otus_hw pull request #5
Opened 2023-07-17 19:50 UTC by pavarov

## Домашнее задание №5 «Параллельное исполнение»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [ ] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [ ] Я запустил `go mod tidy`.
- [ ] Я удалил `.sync` файл. [Зачем его удалять?](https://github.com/OtusGolang/home_work/wiki/%5B%D0%A1%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0%D0%BC%5D-%D0%9F%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81-%D1%81%D0%B4%D0%B0%D1%87%D0%B8-%D0%94%D0%97#user-content-%D0%92%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82-2)
- [ ] Я сравнил объем кода с объемом авторского решения. [Зачем сверять объем кода?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D1%81%D0%B2%D0%B5%D1%80%D1%8F%D1%82%D1%8C-%D0%BE%D0%B1%D1%8A%D0%B5%D0%BC-%D0%BA%D0%BE%D0%B4%D0%B0)
  - run.go ~55 строк

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены новые юнит-тесты - до 4 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2023-07-17 20:04 UTC, pavarov commented on hw05_parallel_execution/run.go
>  	go func() {
нужна ли здесь горутина?

2023-07-17 20:07 UTC, pavarov commented on hw05_parallel_execution/run.go
>  	var errCounter int32
не нравится что по ссылке передаем, но лучше не придумал как посчитать ошибки

2023-07-18 11:14 UTC, ityulkanov requested changes

2023-07-18 11:14 UTC, ityulkanov commented on hw05_parallel_execution/run.go
>  	go func() {
Нет, тут нет необходимости её создавать

2023-07-18 11:14 UTC, ityulkanov commented on hw05_parallel_execution/run.go
>  	var errCounter int32
ошибки нужно или в мьютекс заворачивать при доступе и инкременте, либо атомики использовать, вижу что вы второй вариант выбрали.

2023-07-18 11:14 UTC, ityulkanov commented on hw05_parallel_execution/run.go
> +func consumer(ch chan Task, errCounter *int32, maxErrors int32) {
можно не использовать дополнительную функцию, раз она всё равно не переиспользуется больше нигде, и таким образом избавиться от использования ссылки

2023-07-18 21:30 UTC, ityulkanov approved these changes

2023-07-25 18:14 UTC, merged